name: CI and Deploy

on:
    push:
        branches: ['main', 'master']
    pull_request:
        branches: ['main', 'master']
        types: [opened, reopened, synchronize, closed]
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: ['>=18']

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
                  VITE_BASE_PATH: '/front/pr-preview/pr-${{ github.event.pull_request.number }}/'

            - name: Display environment variables
              run: |
                  echo "VITE_API_URL: ${{ secrets.VITE_API_URL }}"
                  echo "VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}"
                  echo "VITE_BASE_PATH: /front/pr-preview/pr-${{ github.event.pull_request.number }}/"
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
                  VITE_BASE_PATH: '/front/pr-preview/pr-${{ github.event.pull_request.number }}/'

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
                  VITE_BASE_PATH: '/front/pr-preview/pr-${{ github.event.pull_request.number }}/'

            - name: Verify environment variables
              run: |
                  echo "Deployed with VITE_API_URL: ${{ secrets.VITE_API_URL }}"
                  echo "Deployed with VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}"
                  echo "Deployed with VITE_BASE_PATH: /front/pr-preview/pr-${{ github.event.pull_request.number }}/"
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}
                  VITE_BASE_PATH: '/front/pr-preview/pr-${{ github.event.pull_request.number }}/'
