name: CI and Deploy

on:
    push:
        branches: ['main', 'master']
    pull_request:
        branches: ['main', 'master']
        types: [opened, reopened, synchronize, closed]
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: ['>=18']

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
              env:
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
                  VITE_YNDX_API_KEY: ${{ secrets.VITE_YNDX_API_KEY }}

            - name: secrets
              run: echo "My key ${{ secrets.VITE_YNDX_API_KEY }}"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy PR previews
              uses: chvmvd/build-deploy-and-preview-action@v1.2.0
              with:
                  type: vite
